server:
  port: 8040

info:
  name: monitor
  version: 1.0-SNAPSHOT

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZoon: http://localhost:8761/
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
